FROM node:20-slim

WORKDIR /app

RUN apt-get update && apt-get install -y python3 make g++

COPY package*.json ./

RUN npm ci

# Vite's default dev port is 5173
EXPOSE 5173
# HMR port for Vite
EXPOSE 24678


ARG ENV_FILE=.env.dev
ENV $(cat $ENV_FILE | xargs)

CMD ["npm", "run", "start", "--", "--host", "0.0.0.0"]
