version: '3.7'

services:
  nginx:
    image: nginx:1.17
    volumes:
      - ./frontend/nginx/default.conf.dev:/etc/nginx/conf.d/default.conf
    ports:
      - 8000:8000
    depends_on:
      - backend

  postgres:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data:cached

  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ./backend:/app/:cached
      - ./.docker/.ipython:/root/.ipython:cached
    environment:
      PYTHONPATH: .
      DATABASE_URL: 'postgresql://postgres:postgres@postgres:5432/postgres'
      WSDL: ${WSDL}
      LDB_TOKEN: ${LDB_TOKEN}
      ENVIRONMENT: development
    depends_on:
      - "postgres"

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile.dev
    stdin_open: true
    volumes:
      - './frontend:/app:cached'  # Map the whole app directory
      # Exclude node_modules to prevent conflicts
      - '/app/node_modules'
    environment:
      - NODE_ENV=development 
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    ports:
      - "5173:5173"
      - "24678:24678"

volumes:
  db-data:
