version: '3.7'

services:
  frontend:
    image: docker.io/${DOCKERHUB_USER}/${FRONTEND_REPO_NAME}:${VERSION}
    ports:
      - 80:8080
      - 443:8443
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - rtuk-network
    volumes:
      - ./ssl:/etc/nginx/ssl:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro,Z
      - ./certbot/www:/var/www/certbot:ro,Z
      - ./certbot/conf:/etc/letsencrypt:ro,Z
    environment:
      - VITE_API_URL=${VITE_API_URL}
    command: >
          sh -c "
              echo 'Starting nginx...' &&
                  nginx -g 'daemon off;'
                      "
  postgres:
    image: docker.io/postgres:15-alpine
    restart: unless-stopped
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      retries: 3
    volumes:
      - postgres_data:/var/lib/postgresql/data:cached
      - ./backups:/backups
    networks:
      - rtuk-network
    deploy:
      resources:
        limits:
          memory: 1G
        reservations:
          memory: 512M


  backend:
    image: docker.io/${DOCKERHUB_USER}/${BACKEND_REPO_NAME}:${VERSION}
    restart: unless-stopped
    ports:
      - 8080
    environment:
      PYTHONPATH: .
      DATABASE_URL: 'postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}'
      WSDL: ${WSDL}
      LDB_TOKEN: ${LDB_TOKEN}
      ENVIRONMENT: production
      DEBUG: "false"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - rtuk-network
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  rtuk-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
