"""initial migration

Revision ID: 4a653fa94068
Revises: 
Create Date: 2025-09-10 15:19:24.195598

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a653fa94068'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=True),
    sa.Column('last_name', sa.String(), nullable=True),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_app_user_email'), 'app_user', ['email'], unique=True)
    op.create_index(op.f('ix_app_user_id'), 'app_user', ['id'], unique=False)
    op.create_table('known_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.String(), nullable=False),
    sa.Column('origin', sa.String(length=3), nullable=False),
    sa.Column('destination', sa.String(length=3), nullable=False),
    sa.Column('destination_name', sa.String(length=30), nullable=False),
    sa.Column('scheduled_departure', sa.String(length=5), nullable=False),
    sa.Column('calling_points', sa.JSON(), nullable=True),
    sa.Column('operator', sa.String(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_known_services_destination'), 'known_services', ['destination'], unique=False)
    op.create_index(op.f('ix_known_services_destination_name'), 'known_services', ['destination_name'], unique=False)
    op.create_index(op.f('ix_known_services_id'), 'known_services', ['id'], unique=False)
    op.create_index(op.f('ix_known_services_origin'), 'known_services', ['origin'], unique=False)
    op.create_index(op.f('ix_known_services_service_id'), 'known_services', ['service_id'], unique=True)
    op.create_table('profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('origins', sa.String(), nullable=True),
    sa.Column('destinations', sa.String(), nullable=True),
    sa.Column('favourite', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_profiles_id'), 'profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profiles_id'), table_name='profiles')
    op.drop_table('profiles')
    op.drop_index(op.f('ix_known_services_service_id'), table_name='known_services')
    op.drop_index(op.f('ix_known_services_origin'), table_name='known_services')
    op.drop_index(op.f('ix_known_services_id'), table_name='known_services')
    op.drop_index(op.f('ix_known_services_destination_name'), table_name='known_services')
    op.drop_index(op.f('ix_known_services_destination'), table_name='known_services')
    op.drop_table('known_services')
    op.drop_index(op.f('ix_app_user_id'), table_name='app_user')
    op.drop_index(op.f('ix_app_user_email'), table_name='app_user')
    op.drop_table('app_user')
    # ### end Alembic commands ###
