"""empty message

Revision ID: 4d2da0e0de77
Revises: a8e8d97e1fd7
Create Date: 2025-01-21 14:17:36.940809

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d2da0e0de77'
down_revision = 'a8e8d97e1fd7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('known_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.String(), nullable=False),
    sa.Column('origin', sa.String(length=3), nullable=False),
    sa.Column('destination', sa.String(length=3), nullable=False),
    sa.Column('scheduled_departure', sa.String(length=5), nullable=False),
    sa.Column('calling_points', sa.JSON(), nullable=True),
    sa.Column('operator', sa.String(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_known_services_destination'), 'known_services', ['destination'], unique=False)
    op.create_index(op.f('ix_known_services_id'), 'known_services', ['id'], unique=False)
    op.create_index(op.f('ix_known_services_origin'), 'known_services', ['origin'], unique=False)
    op.create_index(op.f('ix_known_services_service_id'), 'known_services', ['service_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_known_services_service_id'), table_name='known_services')
    op.drop_index(op.f('ix_known_services_origin'), table_name='known_services')
    op.drop_index(op.f('ix_known_services_id'), table_name='known_services')
    op.drop_index(op.f('ix_known_services_destination'), table_name='known_services')
    op.drop_table('known_services')
    # ### end Alembic commands ###
