"""empty message

Revision ID: 65b7ba84ec5e
Revises: 7a20819bd40f
Create Date: 2024-06-08 00:51:10.084932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65b7ba84ec5e'
down_revision = '7a20819bd40f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
