"""empty message

Revision ID: 68ca01afba56
Revises: f483bf56bc5d
Create Date: 2025-01-09 22:47:50.387245

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68ca01afba56'
down_revision = 'f483bf56bc5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
