"""empty message

Revision ID: 7a20819bd40f
Revises: b6c29c692770
Create Date: 2024-06-07 15:37:37.829483

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a20819bd40f'
down_revision = 'b6c29c692770'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
