"""favourite?

Revision ID: 8e0c3ec0c7cf
Revises: 68ca01afba56
Create Date: 2025-01-09 22:54:30.037698

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e0c3ec0c7cf'
down_revision = '68ca01afba56'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('favourite', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'favourite')
    # ### end Alembic commands ###
