"""empty message

Revision ID: a8e8d97e1fd7
Revises: 76cae7ac0169
Create Date: 2025-01-13 08:56:21.233301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8e8d97e1fd7'
down_revision = '76cae7ac0169'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('known_services', sa.Column('estimated_departure', sa.String(), nullable=True))
    op.drop_column('known_services', 'etd')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('known_services', sa.Column('etd', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('known_services', 'estimated_departure')
    # ### end Alembic commands ###
