"""empty message

Revision ID: d4eca04b25ba
Revises: 3da9ead79b52
Create Date: 2025-01-12 20:49:56.322122

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd4eca04b25ba'
down_revision = '3da9ead79b52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.String(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('estimated_departure', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=True),
    sa.Column('delay_reason', sa.String(), nullable=True),
    sa.Column('cancel_reason', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['known_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_updates_id'), 'service_updates', ['id'], unique=False)
    op.create_index(op.f('ix_service_updates_service_id'), 'service_updates', ['service_id'], unique=True)
    op.drop_index('ix_train_service_updates_id', table_name='train_service_updates')
    op.drop_index('ix_train_service_updates_service_id', table_name='train_service_updates')
    op.drop_table('train_service_updates')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('train_service_updates',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('service_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('schedule_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('estimated_departure', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('platform', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('is_cancelled', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('delay_reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cancel_reason', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('last_updated', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['known_services.id'], name='train_service_updates_schedule_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='train_service_updates_pkey')
    )
    op.create_index('ix_train_service_updates_service_id', 'train_service_updates', ['service_id'], unique=False)
    op.create_index('ix_train_service_updates_id', 'train_service_updates', ['id'], unique=False)
    op.drop_index(op.f('ix_service_updates_service_id'), table_name='service_updates')
    op.drop_index(op.f('ix_service_updates_id'), table_name='service_updates')
    op.drop_table('service_updates')
    # ### end Alembic commands ###
