"""empty message

Revision ID: d58cce9b7523
Revises: f00a4eb56135
Create Date: 2024-06-08 17:51:37.879360

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd58cce9b7523'
down_revision = 'f00a4eb56135'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
