"""empty message

Revision ID: df3553d27513
Revises: 4d2da0e0de77
Create Date: 2025-01-22 18:35:45.027759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'df3553d27513'
down_revision = '4d2da0e0de77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('known_services', sa.Column('destination_name', sa.String(length=30), nullable=False))
    op.create_index(op.f('ix_known_services_destination_name'), 'known_services', ['destination_name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_known_services_destination_name'), table_name='known_services')
    op.drop_column('known_services', 'destination_name')
    # ### end Alembic commands ###
