"""empty message

Revision ID: e4f121985600
Revises: 
Create Date: 2025-01-12 20:45:44.235387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e4f121985600'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('known_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id_pattern', sa.String(), nullable=False),
    sa.Column('origin_station', sa.String(length=3), nullable=False),
    sa.Column('scheduled_departure', sa.Time(), nullable=False),
    sa.Column('destination_station', sa.String(length=3), nullable=False),
    sa.Column('operator', sa.String(), nullable=True),
    sa.Column('calling_points', sa.JSON(), nullable=True),
    sa.Column('discovered_at', sa.DateTime(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('etd', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=True),
    sa.Column('delay_reason', sa.String(), nullable=True),
    sa.Column('cancel_reason', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_known_services_id'), 'known_services', ['id'], unique=False)
    op.create_index(op.f('ix_known_services_origin_station'), 'known_services', ['origin_station'], unique=False)
    op.create_index(op.f('ix_known_services_service_id_pattern'), 'known_services', ['service_id_pattern'], unique=True)
    op.create_table('train_service_updates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.String(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('estimated_departure', sa.String(), nullable=True),
    sa.Column('platform', sa.String(), nullable=True),
    sa.Column('is_cancelled', sa.Boolean(), nullable=True),
    sa.Column('delay_reason', sa.String(), nullable=True),
    sa.Column('cancel_reason', sa.String(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['known_services.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_train_service_updates_id'), 'train_service_updates', ['id'], unique=False)
    op.create_index(op.f('ix_train_service_updates_service_id'), 'train_service_updates', ['service_id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_train_service_updates_service_id'), table_name='train_service_updates')
    op.drop_index(op.f('ix_train_service_updates_id'), table_name='train_service_updates')
    op.drop_table('train_service_updates')
    op.drop_index(op.f('ix_known_services_service_id_pattern'), table_name='known_services')
    op.drop_index(op.f('ix_known_services_origin_station'), table_name='known_services')
    op.drop_index(op.f('ix_known_services_id'), table_name='known_services')
    op.drop_table('known_services')
    # ### end Alembic commands ###
