"""empty message

Revision ID: e67986ce4e2e
Revises: 2fbee46bd492
Create Date: 2025-01-12 21:34:30.586140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e67986ce4e2e'
down_revision = '2fbee46bd492'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('known_services', sa.Column('origin', sa.String(length=3), nullable=False))
    op.add_column('known_services', sa.Column('destination', sa.String(length=3), nullable=False))
    op.drop_index('ix_known_services_origin_station', table_name='known_services')
    op.create_index(op.f('ix_known_services_destination'), 'known_services', ['destination'], unique=False)
    op.create_index(op.f('ix_known_services_origin'), 'known_services', ['origin'], unique=False)
    op.drop_column('known_services', 'origin_station')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('known_services', sa.Column('origin_station', sa.VARCHAR(length=3), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_known_services_origin'), table_name='known_services')
    op.drop_index(op.f('ix_known_services_destination'), table_name='known_services')
    op.create_index('ix_known_services_origin_station', 'known_services', ['origin_station'], unique=False)
    op.drop_column('known_services', 'destination')
    op.drop_column('known_services', 'origin')
    # ### end Alembic commands ###
