"""added favourite to profile

Revision ID: f483bf56bc5d
Revises: d58cce9b7523
Create Date: 2025-01-09 22:42:15.969216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f483bf56bc5d'
down_revision = 'd58cce9b7523'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
